name: "Rebuild Armbian"
author: "https://github.com/armbian"
description: "Build Armbian Linux"
inputs:

  armbian_target:
    description: "Build image or kernel"
    required: false
    default: "kernel"

  armbian_branch:
    description: "Choose kernel branch"
    required: false
    default: "current"

  armbian_release:
    description: "Choose userspace release"
    required: false
    default: "jammy"

  armbian_version:
    description: "Set different version"
    required: false
    default: ""

  armbian_board:
    description: "Select hardware platform"
    required: false
    default: "uefi-x86"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |

        # translations for easier handling
        BUILD_TARGET="${{ inputs.build_target }}"
        [[ "${{ inputs.armbian_target }}" == image ]] && unset BUILD_TARGET

        # go to build folder
        cd ${GITHUB_ACTION_PATH}

        # execute build command
        ./compile.sh "${BUILD_TARGET}" \
        REVISION="${{ inputs.armbian_version }}" \
        BOARD="${{ inputs.armbian_board }}" \
        BRANCH="${{ inputs.armbian_branch }}" \
        RELEASE="${{ inputs.armbian_release }}" \
        KERNEL_CONFIGURE="no" \
        BUILD_DESKTOP="no" \
        BUILD_MINIMAL="yes"

branding:
  icon: "check"
  color: "red"

