name: "Rebuild Armbian"
author: "https://github.com/armbian"
description: "Build custom Linux for custom hardware"
inputs:
  # Select build target
  build_target:
    description: "Select build target: armbian / kernel"
    required: false
    default: "kernel"
  build_branch:
    description: "Build kernel branch"
    required: false
    default: "current"
  # Images
  armbian_board:
    description: "Set device Board."
    required: false
    default: "all"
  armbian_fstype:
    description: "Set armbian rootfs type: ext4 / btrfs"
    required: false
    default: "ext4"
  builder_name:
    description: "Set Armbian builder signature."
    required: false
    default: ""
  # Kernel
  kernel_branch:
    description: "Set the tags of the stable kernel."
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |

        # translations for easier handling
        BUILD_TARGET="${{ inputs.build_target }}"
        [[ "${{ inputs.build_target }}" == image ]] && unset BUILD_TARGET

        cd ${GITHUB_ACTION_PATH}
        ./compile.sh "${BUILD_TARGET}" \
        BOARD=${{ inputs.armbian_board }} \
        BRANCH=${{ inputs.build_branch }} \
        RELEASE=jammy \
        KERNEL_CONFIGURE=no \
        BUILD_DESKTOP=no \
        BUILD_MINIMAL=yes
        echo ": ->  ${{ inputs.build_target }} ${{ inputs.build_branch }} ${{ inputs.armbian_board }}"

        echo "ARMBIAN_SCRIPT_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV

branding:
  icon: "terminal"
  color: "gray-dark"
