name: "Rebuild Armbian"
author: "https://github.com/armbian"
description: "Build Armbian Linux"
inputs:

  armbian_target:
    description: "Build image or kernel"
    required: false
    default: "kernel"

  armbian_branch:
    description: "Choose kernel branch"
    required: false
    default: "current"

  armbian_release:
    description: "Choose userspace release"
    required: false
    default: "jammy"

  armbian_version:
    description: "Set different version"
    required: false
    default: ""

  armbian_board:
    description: "Select hardware platform"
    required: false
    default: "uefi-x86"

  armbian_ui:
    description: "Armbian user interface"
    required: false
    default: "minimal"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |

        # userspace decode
        if [[ "${{ inputs.armbian_ui }}" == xfce ]]; then
          BUILD_DESKTOP="yes"
          BUILD_MINIMAL="no"
          DESKTOP_ENVIRONMENT="xfce"
          DESKTOP_APPGROUPS_SELECTED=""
          DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base"
        else
          BUILD_DESKTOP="no"
          BUILD_MINIMAL="yes"
          DESKTOP_ENVIRONMENT=""
          DESKTOP_APPGROUPS_SELECTED=""
          DESKTOP_ENVIRONMENT_CONFIG_NAME=""
        fi

        # translations for easier handling
        BUILD_TARGET="${{ inputs.build_target }}"
        [[ "${{ inputs.armbian_target }}" == image ]] && unset BUILD_TARGET

        # go to build folder
        cd ${GITHUB_ACTION_PATH}

        # execute build command
        ./compile.sh "${BUILD_TARGET}" \
        REVISION="${{ inputs.armbian_version }}" \
        BOARD="${{ inputs.armbian_board }}" \
        BRANCH="${{ inputs.armbian_branch }}" \
        RELEASE="${{ inputs.armbian_release }}" \
        KERNEL_CONFIGURE="no" \
        BUILD_DESKTOP="${BUILD_DESKTOP}" \
        BUILD_MINIMAL="${BUILD_MINIMAL}" \
        DESKTOP_ENVIRONMENT="${DESKTOP_ENVIRONMENT}" \
        DESKTOP_APPGROUPS_SELECTED="${DESKTOP_APPGROUPS_SELECTED}" \
        DESKTOP_ENVIRONMENT_CONFIG_NAME="${DESKTOP_ENVIRONMENT_CONFIG_NAME}" \
        COMPRESS_OUTPUTIMAGE="sha,img,xz" \
        SHARE_LOG="yes" \
        EXPERT="yes"

        # save path
        echo "ARMBIAN_SCRIPT_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV

branding:
  icon: "check"
  color: "red"

