name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 */15 * *'
jobs:
  build_on_bionic:
    name: "PUB: sunxi u-boot Docker Bionic"
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v1
     - name: Build Docker image
       shell: bash {0}
       run: |
	sed -i "s/-it --rm/-i --rm/" config/templates/config-docker.conf
	touch .ignore_changes
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" USE_TORRENT="yes" REPOSITORY_INSTALL="kernel"
  build_on_focal:
    name: "PUB: sunxi u-boot Docker Focal"
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v1
     - name: Build Docker image
       shell: bash {0}
       run: |
        sed -i "s/-it --rm/-i --rm/" config/templates/config-docker.conf
        touch .ignore_changes
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" USE_TORRENT="yes" REPOSITORY_INSTALL="kernel"
