name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 */15 * *'
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Build Docker image
       run: |
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" BSP_BUILD="yes" REPOSITORY_INSTALL="u-boot,kernel,armbian-zsh,armbian-config,armbian-firmware" IGNORE_UPDATES="yes"

