name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  call-workflow:
    uses: igorpecovnik/build/.github/workflows/work-b.yml@master

  call-workflow-passing-data:
    uses: igorpecovnik/build/.github/workflows/work-b.yml@master
    with:
      username: mon
