name: Build
on:
  push:
    branches: master
  schedule:
    - cron:  '0 */3 * * *'
jobs:
  build: 
    runs-on: [desktop]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          run-one ./beta-repository.sh
