name: Armbian CI
on:
  push:
    branches: master
  schedule:
    - cron:  '0 */3 * * *'
jobs:
  build: 
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Run script
        shell: bash {0}
        run: |
          echo "test"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: nightly
          clean: false
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/scripts
          token: ${{ secrets.PAT }}
          path: scripts
          clean: false
      - name: Display environment
        shell: bash {0}
        run: |
          echo "BLTPATH=\"$(pwd)/build/\"" > scripts/cacherebuild.conf
          #touch .ignore_changes
          cd build
          pwd
          cd
          cd scripts
          #run-one ./cacherebuild.sh
