name: "Build images XXX"
on:
  workflow_dispatch:
    inputs:

      armbian_target:
        type: choice
        description: 'Build'
        required: false
        options:
        - kernel
        - image

      armbian_branch:
        type: choice
        description: 'Framework build branch'
        options:
        # branches
        - legacy
        - current
        - edge
        default: 'current'

      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        # userspace
        - jammy
        - bookworm
        default: 'jammy'

      armbian_board:
        type: choice
        description: 'Board'
        options:
        # boards
        - bananapicm4io
        - bananapim2pro
        - bananapim2s
        - bananapim5
        - bigtreetech-cb1
        - jethubj100
        - jethubj80
        - khadas-edge2
        - khadas-vim1
        - khadas-vim1s
        - khadas-vim2
        - khadas-vim3
        - khadas-vim3l
        - khadas-vim4
        - lafrite
        - lepotato
        - nanopi-r4s
        - nanopi-r6s
        - nanopiduo
        - nanopiduo2
        - odroidc2
        - odroidm1
        - odroidn2
        - odroidxu4
        - olimex-teres-a64
        - onecloud
        - orangepi-r1
        - orangepi-r1plus-lts
        - orangepi4-lts
        - orangepi5-plus
        - orangepi5
        - orangepione
        - orangepiprime
        - orangepizero
        - orangepizero2
        - orangepizeroplus
        - pine64
        - pinebook-pro
        - radxa-zero
        - renegade
        - rock-3a
        - rock-5b
        - rockpi-4a
        - rockpi-e
        - rockpro64
        - rpi4b
        - rpi5b
        - sk-am62b
        - sk-am64b
        - sk-tda4vm
        - tinkerboard
        - tritium-h3
        - tritium-h5
        - uefi-arm64
        - uefi-x86
        - xiaomi-elish
        default: 'uefi-x86'

      armbian_version:
        description: 'Version'
        required: false
        default: '23.11.1'

jobs:

  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    steps:

      #- name: Update
      #  run: |
      #    sudo apt update
      #    sudo apt -y upgrade

      #- name: Free Github Runner
      #  if: inputs.BUILD_RUNNER == 'ubuntu-latest'
      #  uses: descriptinc/free-disk-space@main
      #  with:
      #    android: true
      #    dotnet: true
      #    haskell: true
      #    large-packages: true
      #    docker-images: true
      #    swap-storage: true

      - name: "Compile ${{ inputs.build_target }}"
        uses: igorpecovnik/build@main
        with:
          armbian_target:   "${{ inputs.armbian_target }}"
          armbian_branch:   "${{ inputs.armbian_branch }}"
          armbian_release:  "${{ inputs.armbian_release }}"
          armbian_version:  "${{ inputs.armbian_version }}"
          armbian_board:    "${{ inputs.armbian_board }}"

      - name: Calculate upload path
        run: |
          if [[ "${{ inputs.build_target }}" == image ]]; then
            echo "ARMBIAN_SCRIPT_PATH=${{ env.ARMBIAN_SCRIPT_PATH }}/output/images/" >> $GITHUB_ENV
          else
            echo "ARMBIAN_SCRIPT_PATH=${{ env.ARMBIAN_SCRIPT_PATH }}/output/debs/" >> $GITHUB_ENV
          fi

      - uses: ncipollo/release-action@v1
        with:
          tag: "Armbian ${{ inputs.build_target }}"
          artifacts: "${{ env.ARMBIAN_SCRIPT_PATH }}*"
          omitBody: true
          omitName: true
          allowUpdates: true
          removeArtifacts: true
          makeLatest: true
          token: "${{ secrets.GITHUB_TOKEN }}"
