name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build Docker image
      run: |
       sed -i "s/-it --rm/-i --rm/" config/templates/config-docker.conf
       touch .ignore_changes
       ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" USE_TORRENT="yes" REPOSITORY_INSTALL="kernel"
       docker tag armbian:$(cat VERSION) armbian/build:latest
    - name: Push Docker image
      run: docker push ghcr.io/igorpecovnik/build:latest
